"""tools/render_chart.py had zero test coverage before this file. That is how
the chart's x-axis ended up hardcoded to 24 (the old max score) and silently
wrong the moment a category was added and the real max became 32 - the axis
label lied and, worse, would have clipped any bar past 24 without complaint.

These tests exist so a future change to the category count fails loudly here
instead of shipping a wrong chart.
"""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from tools.patterns import CATEGORIES
from tools.render_chart import THEMES, by_category_chart, by_draft_chart, main

REPO_ROOT = Path(__file__).resolve().parent.parent
LATEST = REPO_ROOT / "evals/results/latest.json"


def _fake_data(scorer_max: int) -> dict:
    """A minimal, schema-correct results payload for a hypothetical scorer
    with a different category count, so the chart is tested against more than
    just whatever the current live category count happens to be."""
    return {
        "meta": {
            "model": "sonnet",
            "repeats": 3,
            "arms": ["baseline", "generic", "skill"],
            "generated_at": "2026-01-01T00:00:00Z",
            "scorer_max": scorer_max,
        },
        "summary": {
            "by_draft": {
                "example": {"draft": scorer_max - 1, "baseline": 8, "generic": 7, "skill": 3},
            },
            "by_category": {
                "made_up_category": {
                    "name": "Made-up category",
                    "draft": 2,
                    "baseline": 1,
                    "generic": 1,
                    "skill": 0,
                },
            },
        },
    }


@pytest.mark.parametrize("scorer_max", [24, 32, 40])
def test_by_draft_axis_tracks_scorer_max(scorer_max):
    """The regression test for the actual bug: the axis must scale with
    whatever scorer produced the data, not with a number written down once."""
    svg = by_draft_chart(_fake_data(scorer_max), THEMES["light"])
    assert f"0-{scorer_max}" in svg
    assert f"sum of {scorer_max // 2} audit categories" in svg
    # The old hardcoded value must not leak in when the real max is different.
    if scorer_max != 24:
        assert "0-24" not in svg


def test_by_draft_chart_is_well_formed_svg():
    svg = by_draft_chart(_fake_data(32), THEMES["light"])
    root = ET.fromstring(svg)
    assert root.tag.endswith("svg")


def test_by_category_chart_is_well_formed_svg():
    svg = by_category_chart(_fake_data(32), THEMES["dark"])
    root = ET.fromstring(svg)
    assert root.tag.endswith("svg")


def test_chart_labels_do_not_overflow_a_hardcoded_bar_count():
    """A chart with more rows than the current live category count must still
    render every row - nothing here should be sized for exactly 12 or 16."""
    data = _fake_data(32)
    data["summary"]["by_category"] = {
        f"cat_{i}": {"name": f"Category {i}", "draft": 2, "baseline": 1, "generic": 1, "skill": 0}
        for i in range(20)
    }
    svg = by_category_chart(data, THEMES["light"])
    for i in range(20):
        assert f"Category {i}" in svg


def test_live_charts_match_the_live_scorer():
    """The committed evals/results/latest.json should describe exactly as
    many categories as tools/patterns.py currently defines - if this drifts,
    the chart axis is describing a scorer that no longer exists."""
    if not LATEST.exists():
        pytest.skip("no committed eval results to check")
    meta = json.loads(LATEST.read_text(encoding="utf-8"))["meta"]
    assert meta["scorer_max"] == 2 * len(CATEGORIES), (
        "evals/results/latest.json was generated by a different category count "
        "than tools/patterns.py currently defines - regenerate it with "
        "`python evals/run_eval.py` (or rescore the existing raw texts) and "
        "`python -m tools.render_chart`"
    )


def test_main_writes_all_four_files(tmp_path):
    out_dir = tmp_path / "assets"
    results = tmp_path / "latest.json"
    results.write_text(json.dumps(_fake_data(32)), encoding="utf-8")
    assert main([str(results), "--out-dir", str(out_dir)]) == 0
    written = sorted(p.name for p in out_dir.glob("*.svg"))
    assert written == [
        "slopscore-by-category-dark.svg",
        "slopscore-by-category-light.svg",
        "slopscore-by-draft-dark.svg",
        "slopscore-by-draft-light.svg",
    ]
